### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1

### ISSUE THREAD

**Issue by nileshpambhar** [applidium/HeaderListView#58]
Hello,

When i have bind listview with real data. i am getting below error. with out scrolling listview it is working fine. but once i scroll page then its crash app.

Please check screenshot
![screenshot](https://cloud.githubusercontent.com/assets/15199910/24185015/da308cfc-0ef6-11e7-8318-ac5cb07f54b6.png)

**java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
                                                                                      at java.util.ArrayList.get(ArrayList.java:310)
                                                                                      at com.applidium.headerlistviewdemo.DemoActivity$1.numberOfRows(DemoActivity.java:43)
                                                                                      at com.applidium.headerlistview.HeaderListView$HeaderListViewOnScrollListener.onScroll(HeaderListView.java:151)**

Please check my code...

[DemoActivity.txt](https://github.com/applidium/HeaderListView/files/860518/DemoActivity.txt)

**Comment by HiteshRaviya** [comment]
Hello,

inside **Headerlistview** 
     boolean prevHasRows = mAdapter.numberOfRows(actualSection - 1) > 0;
Replace  boolean prevHasRows = mAdapter.numberOfRows(actualSection ) > 0;

**Comment by mortenholmgaard** [comment]
There is actually a lot of errors with calls with section -1. For example to hasSectionHeaderView(section)

Another critical one if handling multiple headers with different sizes is the need to add:
```
            if (actualSection < 0)
                actualSection = 0;
```
To **addSectionHeader(int actualSection)**
